name: Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.9.0
      - run: ./gradlew build